# Generated by Django 4.1 on 2023-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bharatarchive_api", "0002_alter_language_language_code_alpha2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cms_tabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_name", models.CharField(max_length=25)),
                ("tab_dsiplay_name", models.CharField(max_length=25)),
                ("tab_endpoint", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=1)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=100)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Content Management System Website Tabs",
            },
        ),
        migrations.CreateModel(
            name="cms_views",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=25)),
                ("footer_text", models.CharField(max_length=200)),
                ("change_theme_tooltip", models.CharField(max_length=50)),
                ("menu_tooltip", models.CharField(max_length=50)),
                ("logo_tooltip", models.CharField(max_length=50)),
                ("created_by", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=100)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Content Management System Website Views",
            },
        ),
    ]
